Update git-recall

diff --git a/bin/git-recall b/bin/git-recall
--- a/bin/git-recall
+++ b/bin/git-recall
@@ -3,7 +3,6 @@
 # Credit to:
 #   https://github.com/Fakerr/git-recall
 
-
 # usage info
 usage() {
   cat <<EOF
@@ -13,89 +12,100 @@ usage() {
     -a, --author            Author name.
     -f, --fetch             fetch commits.
     -h, --help              This message.
+    -v, --version           Show version.
     --                      End of options.
 EOF
 }
 
-
 # Global variables
-SINCE="1 days ago" # show logs for last day by default
 AUTHOR=""
 FETCH=false
 GIT_FORMAT=""
 GIT_LOG=""
 COMMITS=""
-VERSION="1.1.1"
+SINCE="1 days ago"     # show logs for last day by default
+COMMITS_UNCOL=()       # commits without colors
+SED_CMD=""             # Sed command to use according OS.
+LESSKEY=false
+VERSION="1.2.1"
 
-# Are we in a git repo?
-if [[ ! -d ".git" ]]; then
-  echo "abort: not a git repository." 1>&2
-  exit 1
-fi
-
-# Parse options
-while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do
-  case $1 in
-    -v | --version )
-      echo $version
-      exit
-      ;;
-    -d | --date )
-      SINCE="$2 days ago"
-      shift;
-      ;;
-    -a | --author )
-      AUTHOR="$2"
-      shift
-      ;;
-    -f | --fetch )
-      FETCH=true
-      ;;
-    -h | --help )
-      usage
-      exit
-      ;;
-    * )
-      echo "abort: unknown argument" 1>&2
-      exit 1
-  esac
-  shift
-done
-if [[ "$1" == "--" ]]; then shift; fi
-
+# Set key bindings.
+au="`echo -e '\e[A'`" # arrow up
+ad="`echo -e '\e[B'`" # arrow down
+ec="`echo -e '\e'`"   # escape
+nl="`echo -e '\n'`"   # newline
+au_1="k"              # arrow up
+ad_1="j"              # arrow down
+nl_1="e"              # expand
 
 # Colored output.
 function colored() {
-  GREEN=$(tput setaf 4)
-  YELLOW=$(tput setaf 3)
-  NORMAL=$(tput sgr0)
-  REVERSE=$(tput rev)
+    GREEN=$(tput setaf 4)
+    YELLOW=$(tput setaf 3)
+    NORMAL=$(tput sgr0)
+    REVERSE=$(tput rev)
 } 
 
 # Uncolored output.
 function uncolored() {
-  GREEN=""
-  YELLOW=""
-  NORMAL=""
-  REVERSE=""
+    GREEN=""
+    YELLOW=""
+    NORMAL=""
+    REVERSE=""
 }
+
+# Clear screen from cursor to end of screen
+function clear_screen() {
+    echo -e "\E[J"
+    tput cuu1
+}
+
+# Are we in a git repo?
+if [[ ! -d ".git" ]] && ! git rev-parse --git-dir &>/dev/null; then
+    echo "abort: not a git repository." 1>&2
+    exit 1
+fi
+
+# Parse options
+while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do
+    case $1 in
+	-v | --version )
+	    echo "$VERSION"
+	    exit
+	    ;;
+	-d | --date )
+	    SINCE="$2 days ago"
+	    shift;
+	    ;;
+	-a | --author )
+	    AUTHOR="$2"
+	    shift
+	    ;;
+	-f | --fetch )
+	    FETCH=true
+	    ;;
+	-h | --help )
+	    usage
+	    exit
+	    ;;
+	* )
+	    echo "abort: unknown argument" 1>&2
+	    exit 1
+    esac
+    shift
+done
+if [[ "$1" == "--" ]]; then shift; fi
 
 # Enable colors if supported by terminal.
 if [[ -t 1 ]] && [[ -n "$TERM" ]] && which tput &>/dev/null && tput colors &>/dev/null; then
-  ncolors=$(tput colors)
-  if [[ -n "$ncolors" ]] && [[ "$ncolors" -ge 8 ]] ; then
-    colored
-  else
-    uncolored
-  fi
+    ncolors=$(tput colors)
+    if [[ -n "$ncolors" ]] && [[ "$ncolors" -ge 8 ]] ; then
+	colored
+    else
+	uncolored
+    fi
 else
-  uncolored
-fi
-
-# Check if lesskey is correctly installed.
-if ! which lesskey &>/dev/null; then
-  echo "abort: the program lesskey is not installed. Make sure to install it before running git-recall" 1>&2
-  exit 1
+    uncolored
 fi
 
 # Set AUTHOR to current user if no param passed or display for all users if param equal to "all". 
@@ -110,7 +120,7 @@ if [[ $FETCH == true ]]; then
     echo "${GREEN}Fetching changes...${NORMAL}"
     git fetch --all &> /dev/null
     tput cuu1
-    tput ed # clear screen
+    clear_screen
 fi
 
 # Log template.
@@ -126,65 +136,90 @@ IFS=$'\n'
 COMMITS=($(eval ${GIT_LOG} 2>/dev/null))
 unset IFS
 
-NI=${#COMMITS[@]} # Total number of items.
-SN=$(( `tput lines` - 1 )) # Screen number of lines.
-TN=$(( $NI < $((SN -1)) ? $NI : $((SN -1)))) # Number of lines that we will display.
+NI=${#COMMITS[@]}                             # Total number of items.
+SN=$(( `tput lines` - 1 ))                    # Screen's number of lines.
+CN=$(tput cols)                               # Screen's number of columns.
+TN=$(( $NI < $((SN -1)) ? $NI : $((SN -1))))  # Number of lines that we will display.
+OFFSET=0                                      # Incremented by one each time a commit's length is higher than teminal width.
 
 # If there is no items, exit.
 if [[ $NI = 0 ]]; then
     if [[ $AUTHOR = ".*" ]]; then
-	echo "${YELLOW}All contributors did nothing during this period.${NORMAL}" && exit 0
+   	echo "${YELLOW}All contributors did nothing during this period.${NORMAL}" && exit 0
     else
-	echo "${YELLOW}The contributor \"${AUTHOR}\" did nothing during this period.${NORMAL}" && exit 0
+   	echo "${YELLOW}The contributor \"${AUTHOR}\" did nothing during this period.${NORMAL}" && exit 0
     fi
 fi
 
-# Set keys.
-au="`echo -e '\e[A'`" # arrow up
-au_1="k"              # arrow up
-ad="`echo -e '\e[B'`" # arrow down
-ad_1="j"              # arrow down
-ec="`echo -e '\e'`"   # escape
-nl="`echo -e '\n'`"   # newline
+# Check if lesskey is installed.
+if command -v lesskey &> /dev/null; then
+    LESSKEY=true
+fi
+
+# Set correct sed command according OS's type
+case "$OSTYPE" in
+    darwin*) SED_CMD="sed -E s/"$'\E'"\[([0-9]{1,2}(;[0-9]{1,2})*)?m//g" ;;
+    *)       SED_CMD="sed -r s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g" ;;
+esac
+
+# Create array with uncolred commits (removing escape sequences using sed)
+for elt in "${COMMITS[@]}"
+do
+    ELT="$(echo "$elt" | $SED_CMD)" # remove colors escape codes
+    COMMITS_UNCOL+=("$ELT")
+done
+
+# Add +1 to OFFSET if a commit's length is bigger than the current terminal session's width. (This is to fix a redraw issue)
+for C in "${COMMITS_UNCOL[@]}"
+do
+    if [[ ${#C} -gt $CN ]]; then
+	OFFSET=$(( OFFSET + 1 ))
+    fi
+done
 
 # Create a temporary lesskey file to change the keybindings so the user can use the TAB key to quit less. (more convenient)  
-echo "\t quit" | lesskey -o $HOME/.lsh_less_keys_tmp -- - &> /dev/null
+if [[ $LESSKEY = true ]]; then
+    echo "\t quit" | lesskey -o /tmp/lsh_less_keys_tmp -- - &> /dev/null
+fi
 
-## Get commit's diff.
+# Get commit's diff.
 function get_diff() {
-    ELT="$(echo "${COMMITS[$CP-1]}" | sed -r "s/\x1B\[([0-9]{1,2}(;[0-9]{1,2})?)?[m|K]//g")" # remove colors escape codes
+    ELT="$(echo "${COMMITS_UNCOL[$CP-1]}")"
     DIFF_TIP=${ELT:0:7}
     DIFF_CMD="git show $DIFF_TIP --color=always"
     DIFF=$(eval ${DIFF_CMD} 2>/dev/null)
+    tmp_diff="$(echo "$DIFF" | $SED_CMD)"
+    off=$(echo "$tmp_diff" | grep -c ".\{$CN\}") # Number of lines in the diff that are longer than terminal width.
     DIFF_LINES_NUMBER="$(echo "$DIFF" | wc -l)"
+    DIFF_LINES_NUMBER=$(( DIFF_LINES_NUMBER + off ))
 }
 
-## This function will print the diff according the commit's tip. If the diff is too long, the result will be displayed using 'less'. 
+# This function will print the diff according the commit's tip. If the diff is too long, the result will be displayed using 'less'. 
 function print_diff() {
-    
     get_diff
-
-    if [[ $(( TN + DIFF_LINES_NUMBER )) -ge $(( `tput lines` - 1 )) ]]; then
-	echo -e "$REVERSE ${COMMITS[$CP - 1]}\n\n $DIFF" | less -r -k $HOME/.lsh_less_keys_tmp
+    if [[ $(( TN + DIFF_LINES_NUMBER + OFFSET )) -ge $(( `tput lines` - 1 )) ]]; then
+	if [[ $LESSKEY = true ]]; then
+	    echo "$DIFF" | less -r -k /tmp/lsh_less_keys_tmp
+	else 
+	    echo "$DIFF" | less -r
+	fi
+	clear_screen
     else 
 	stop=false
-	tput ed
+	clear_screen
 	for i in `seq 1 $TN`
 	do
 	    echo -n "$NORMAL"
-	    [[ $CP == $i ]] && echo -n "$REVERSE"
+	    [[ $CP == "$i" ]] && echo -n "$REVERSE"
 	    echo "${COMMITS[$i - 1]}"
-	
-	    if [[ $CP == $i ]]; then
-	        echo "$DIFF"
-	    fi
+	    [[ $CP == "$i" ]] && echo "$DIFF"
 	done
-
+	# Wait for user action.
 	while ! $stop
 	do
 	    read -sn 1 key
 	    case "$key" in
-		"$nl")
+		"$nl" | "$nl_1")
 		    stop=true
 		    ;;
 		"q")
@@ -193,77 +228,109 @@ function print_diff() {
 		    ;;
 	    esac
 	done
-	[[ $END = false ]] && tput cuu $(( TN + DIFF_LINES_NUMBER )) && tput ed
+	[[ $END = false ]] && tput cuu $(( TN + DIFF_LINES_NUMBER + OFFSET )) && clear_screen
 	[[ $END = true ]] && tput cuu 1
     fi
 }
 
+# Calculate OFFSET to avoid bad redraw.
+function calculate_offset {
+    tmp=1
+    index=$(( SI -1 ))
+    while [[ $tmp -lt $SN ]]
+    do
+    	el=${COMMITS_UNCOL[$index]}
+    	if [[ ${#el} -gt $CN ]] && [[ $CP -lt $((SN -1)) ]]; then
+    	    OFFSET_2=$(( OFFSET_2 + 1 ))
+    	    tmp=$(( tmp + 1 ))
+    	fi
+    	tmp=$(( tmp + 1 ))
+    	index=$(( index + 1 ))
+    done
+}
 
 { # capture stdout to stderr
 
-tput civis # hide cursor.
-CP=1 # current position
-SI=1 # index
-END=false # end while loop
+tput civis   # hide cursor.
+CP=1         # current position
+SI=1         # index
+END=false    # end while loop
+EXT=0        # Used to extend the number of lines to display.
 
-## Loops, reads inputs and prints commits until user presses 'q' to exit or TAB to show the diff.
 while ! $END
 do
+    # When the number of item is higher than screen's number of lines, OFFSET_2 is recalculated each time we select a new item.
+    # Set last index to print. (based on OFFSET)
+    END_INDEX=0 # Index for the last item to display
+    if [[  $TN == $NI ]]; then 
+	END_INDEX=$TN
+	OFFSET_2=$OFFSET
+    elif [[  $TN == $(( SN - 1 )) ]]; then
+	# Calculate new OFFSET.
+	if [[ $OFFSET != 0 ]]; then 
+   	    [[ $CP -lt $((SN -1)) ]] && OFFSET_2=0
+   	    EXT=1
+   	    calculate_offset
+	fi
+	END_INDEX=$(( TN + SI -1 + EXT - OFFSET_2 ))
+    fi
 
-   for i in `seq $SI $(( $TN + $SI -1 ))`
-   do
-      echo -n "$NORMAL"
-      [[ $CP == $i ]] && echo -n "$REVERSE"
-      echo "${COMMITS[$i - 1]}"
-   done
+    # Loop and echo commits
+    for i in `seq $SI $END_INDEX`
+    do
+	echo -n "$NORMAL"
+	[[ $CP == $i ]] && echo -n "$REVERSE"
+	echo "${COMMITS[$i - 1]}"
+    done
 
-   read -sn 1 key
-   [[ "$key" == "$ec" ]] &&
-   {
-      read -sn 2 k2
-      key="$key$k2"
-   }
+    read -sn 1 key
+    [[ "$key" == "$ec" ]] &&
+    {
+	read -sn 2 k2
+	key="$key$k2"
+    }
 
-   case "$key" in
+    case "$key" in
+	"$au" | "$au_1")
+            CP=$(( CP - 1 ))
+            [[ $CP == 0 ]] && [[ $SI == 1 ]] && [[ $TN == $(( SN - 1 )) ]] && CP=$NI && SI=$(( NI - SN + 2 + OFFSET_2 ))
+            [[ $CP == 0 ]] && [[ $SI == 1 ]] && [[ $TN == $NI ]] && CP=$TN
+            [[ $CP == $(( SI - 1 )) ]] && [[ $SI != 1 ]] && SI=$(( SI - 1 ))
 
-      "$au" | "$au_1")
-         CP=$(( CP - 1 ))
-         [[ $CP == 0 ]] && [[ $SI=1 ]] && [[ $TN == $(( SN - 1 )) ]] && CP=$NI && SI=$(( NI - SN + 2 ))
-         [[ $CP == 0 ]] && [[ $SI=1 ]] && [[ $TN == $NI ]] && CP=$TN
-         [[ $CP == $(( SI - 1 )) ]] && [[ $SI != 1 ]] && SI=$(( SI - 1 ))
-	 tput cuu $TN
-         [[ $SI != 1 ]] && tput ed # clear screen
-         ;;
+   	    [[ $TN != $(( SN - 1 )) ]] && tput cuu $(( TN + OFFSET_2 ))
+   	    [[ $TN == $(( SN - 1 )) ]] && tput cuu $(( TN + EXT ))
+            [[ $SI != 1 ]] && clear_screen
+            ;;
+	"$ad" | "$ad_1")
+   	    CP=$(( CP + 1 ))
+            [[ $CP == $(( NI + 1 )) ]] && CP=1 && SI=1 
+            [[ $CP == $(( SN + SI - 1 + EXT - OFFSET_2 )) ]] && [[ $TN == $(( SN - 1 )) ]] && SI=$(( SI + 1 ))
 
-      "$ad" | "$ad_1")
-	 CP=$(( CP + 1 ))
-         [[ $CP == $(( NI + 1 )) ]] && CP=1 && SI=1 
-         [[ $CP == $(( SN + SI - 1)) ]] && [[ $TN == $(( SN - 1 )) ]] && SI=$(( SI + 1 ))
-	 tput cuu $TN
-         [[ $SI != 1 ]] && tput ed # clear screen
-         [[ $SI = 1 ]] && [[ $CP = 1 ]] && tput ed # clear screen
-         ;;
-
-      "$nl")
-	  tput cuu $TN
-          print_diff 
-         ;;
-
-      "q")
-         si=false
-         END=true
-	 tput cuu 1
-         ;;
-
-      * )
-	 tput cuu $TN
-   esac
-
+   	    [[ $TN != $(( SN - 1 )) ]] && tput cuu $(( TN + OFFSET_2 ))
+   	    [[ $TN == $(( SN - 1 )) ]] && tput cuu $(( TN + EXT ))
+            [[ $SI != 1 ]] && clear_screen
+            [[ $SI = 1 ]] && [[ $CP = 1 ]] && clear_screen
+            ;;
+	"$nl" | "$nl_1")
+   	    [[  $TN == $NI ]] && tput cuu $(( TN + OFFSET_2 ))
+   	    [[  $TN != $NI ]] && tput cuu $(( TN + EXT ))
+            print_diff 
+            ;;
+	"q")
+            si=false
+            END=true
+   	    tput cuu 1 #move cursor up one line. (remove extra line)
+            ;;
+	* )
+   	    tput cuu $(( TN + OFFSET_2 ))
+    esac
 done
 
-rm $HOME/.lsh_less_keys_tmp # remove temporary less keybindings
-tput cnorm # unhide cursor
-echo "$NORMAL" # normal colors
+# remove temporary less keybindings
+[[ $LESSKEY = true ]] && rm /tmp/lsh_less_keys_tmp 
+
+tput cnorm      # unhide cursor
+echo "$NORMAL"  # normal colors
 
 } >&2 # END capture
 
