Update git-recall

diff --git a/bin/git-recall b/bin/git-recall
--- a/bin/git-recall
+++ b/bin/git-recall
@@ -10,6 +10,8 @@ usage() {
   Options:
     -d, --date              Show logs for last n days.
     -a, --author            Author name.
+    -b, --branch            Specify branch to display commits from.
+    -p  --path              Specify path or filename to display commits from.
     -f, --fetch             fetch commits.
     -h, --help              This message.
     -v, --version           Show version.
@@ -18,6 +20,7 @@ EOF
 }
 
 # Global variables
+orig_stty=$(stty -g)   # Store original terminal settings
 AUTHOR=""
 FETCH=false
 GIT_FORMAT=""
@@ -27,7 +30,9 @@ SINCE="1 days ago"     # show logs for last day by default
 COMMITS_UNCOL=()       # commits without colors
 SED_CMD=""             # Sed command to use according OS.
 LESSKEY=false
-VERSION="1.2.1"
+VERSION="1.2.4"
+BRANCH=""
+SEARCH_PATH=""
 
 # Set key bindings.
 au="`echo -e '\e[A'`" # arrow up
@@ -88,6 +93,14 @@ while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do
 	    usage
 	    exit
 	    ;;
+	-b | --branch )
+            BRANCH="$2"
+            shift
+            ;;
+        -p | --path )
+            SEARCH_PATH="$2"
+            shift
+            ;;
 	* )
 	    echo "abort: unknown argument" 1>&2
 	    exit 1
@@ -129,7 +142,7 @@ GIT_FORMAT="%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%a
 # Log command.
 GIT_LOG="git log --pretty=format:'${GIT_FORMAT}'  
            --author \"$AUTHOR\"
-           --since \"$SINCE\" --abbrev-commit"
+           --since \"$SINCE\" --abbrev-commit --no-merges $BRANCH $SEARCH_PATH"
 
 # Change temporary the IFS to store GIT_LOG's output into an array.
 IFS=$'\n'
@@ -186,7 +199,7 @@ fi
 function get_diff() {
     ELT="$(echo "${COMMITS_UNCOL[$CP-1]}")"
     DIFF_TIP=${ELT:0:7}
-    DIFF_CMD="git show $DIFF_TIP --color=always"
+    DIFF_CMD="git show $DIFF_TIP --color=always $SEARCH_PATH"
     DIFF=$(eval ${DIFF_CMD} 2>/dev/null)
     tmp_diff="$(echo "$DIFF" | $SED_CMD)"
     off=$(echo "$tmp_diff" | grep -c ".\{$CN\}") # Number of lines in the diff that are longer than terminal width.
@@ -198,11 +211,13 @@ function get_diff() {
 function print_diff() {
     get_diff
     if [[ $(( TN + DIFF_LINES_NUMBER + OFFSET )) -ge $(( `tput lines` - 1 )) ]]; then
+	trap - INT
 	if [[ $LESSKEY = true ]]; then
 	    echo "$DIFF" | less -r -k /tmp/lsh_less_keys_tmp
 	else 
 	    echo "$DIFF" | less -r
 	fi
+	trap cleanup_and_exit INT
 	clear_screen
     else 
 	stop=false
@@ -229,7 +244,6 @@ function print_diff() {
 	    esac
 	done
 	[[ $END = false ]] && tput cuu $(( TN + DIFF_LINES_NUMBER + OFFSET )) && clear_screen
-	[[ $END = true ]] && tput cuu 1
     fi
 }
 
@@ -248,6 +262,21 @@ function calculate_offset {
     	index=$(( index + 1 ))
     done
 }
+
+# Reset changes made by this script before exiting
+function cleanup_and_exit() {
+    # remove temporary less keybindings
+    [[ $LESSKEY = true ]] && rm /tmp/lsh_less_keys_tmp
+
+    tput cuu 1      # move cursor up one line. (remove extra line)
+    tput cnorm      # unhide cursor
+    echo "$NORMAL"  # normal colors
+    stty "$orig_stty" > /dev/null 2>&1
+    exit
+}
+
+# Catch a control-C interrupt and perform cleanup operations before exiting
+trap cleanup_and_exit INT
 
 { # capture stdout to stderr
 
@@ -319,18 +348,13 @@ do
 	"q")
             si=false
             END=true
-   	    tput cuu 1 #move cursor up one line. (remove extra line)
             ;;
 	* )
    	    tput cuu $(( TN + OFFSET_2 ))
     esac
 done
 
-# remove temporary less keybindings
-[[ $LESSKEY = true ]] && rm /tmp/lsh_less_keys_tmp 
-
-tput cnorm      # unhide cursor
-echo "$NORMAL"  # normal colors
+cleanup_and_exit
 
 } >&2 # END capture
 
